version: "3"

services:
  server:
    build: .
    ports:
      - "5000:5000"
    environment:
      - API_KEY=1d81103567524b21a8777fd705eb4e5d
      - NY_TIMES_API_KEY=RpXloCWt8Qq3w9aH1eXsOSyujKcmqyeW
